export enum County {
  ZagrebackaZupanija = 'Zagrebačka',
  KrapinskoZagorskaZupanija = 'Krapinsko-zagorska',
  SisackoMoslavackaZupanija = 'Sisačko-moslavačka',
  KarlovackaZupanija = 'Karlovačka',
  VarazdinskaZupanija = 'Varaždinska',
  KoprivnickoKrizevackaZupanija = 'Koprivničko-križevačka',
  BjelovarskoBilogorskaZupanija = 'Bjelovarsko-bilogorska',
  PrimorskoGoranskaZupanija = 'Primorsko-goranska',
  LickoSenjskaZupanija = 'Ličko-senjska',
  VirovitickoPodravskaZupanija = 'Virovitičko-podravska',
  PozeskoSlavonskaZupanija = 'Požeško-slavonska',
  BrodskoPosavskaZupanija = 'Brodsko-posavska',
  ZadarskaZupanija = 'Zadarska',
  OsjeckoBaranjskaZupanija = 'Osječko-baranjska',
  SibenskoKninskaZupanija = 'Šibensko-kninska',
  VukovarskoSrijemskaZupanija = 'Vukovarsko-srijemska',
  SplitskoDalmatinskaZupanija = 'Splitsko-dalmatinska',
  IstarskaZupanija = 'Istarska',
  DubrovackoNeretvanskaZupanija = 'Dubrovačko-neretvanska',
  MedimurskaZupanija = 'Međimurska',
  GradZagreb = 'Grad Zagreb',
}
