export enum County {
  'Zagrebačka županija' = 'Zagrebačka',
  'Krapinsko-zagorska županija' = 'Krapinsko-zagorska',
  'Sisačko-moslavačka županija' = 'Sisačko-moslavačka',
  'Karlovačka županija' = 'Karlovačka',
  'Varaždinska županija' = 'Varaždinska',
  'Koprivničko-križevačka županija' = 'Koprivničko-križevačka',
  'Bjelovarsko-bilogorska županija' = 'Bjelovarsko-bilogorska',
  'Primorsko-goranska županija' = 'Primorsko-goranska',
  'Ličko-senjska županija' = 'Ličko-senjska',
  'Virovitičko-podravska županija' = 'Virovitičko-podravska',
  'Požeško-slavonska županija' = 'Požeško-slavonska',
  'Brodsko-posavska županija' = 'Brodsko-posavska',
  'Zadarska županija' = 'Zadarska',
  'Osječko-baranjska županija' = 'Osječko-baranjska',
  'Šibensko-kninska županija' = 'Šibensko-kninska',
  'Vukovarsko-srijemska županija' = 'Vukovarsko-srijemska',
  'Splitsko-dalmatinska županija' = 'Splitsko-dalmatinska',
  'Istarska županija' = 'Istarska',
  'Dubrovačko-neretvanska županija' = 'Dubrovačko-neretvanska',
  'Međimurska županija' = 'Međimurska',
  'Grad Zagreb' = 'Grad Zagreb',
}
